### ISSUE TITLE
Assign categories to closed conversations

### ISSUE THREAD

**Issue by 0ndifined** [mrsimpson/Rocket.Chat#71]
**Current state**
When closing a conversation, it currently shows an empty text field. 

**Preferred state**
To help categorization of closed conversations, there should be a list of categories when closing a conversation. The user can then assign categories to the closed conversation. There needs to be a way to configure the list of categories (add, edit, remove)

**Comment by mrsimpson** [comment]
This issue was moved to assistify/Rocket.Chat#15

**Comment by ruKurz** [comment]
This close dialog is purposed for reporting. Since the requirements can be very individual here, the dialog should perform a configurable form, that allows to categorize, add some meta data and offer some predefined selections.

This dialog should be optional, and therefor an activation / deactivation is required:
https://github.com/assistify/Rocket.Chat/issues/24
