### ISSUE TITLE
Opening user profile in "expertise" channels is not possible

### ISSUE THREAD

**Issue by janrudolph** [mrsimpson/Rocket.Chat#88]
**Situation**
An Expert, who owns an "expertise" channel, likes to add a new moderator or owner. In a regular channel, the expert would open the right sidebar and would select a user in the user list. The expert would then be able to set the permission in the user profile which will appear. 

**Problem**
In "expertise" channels it is not possible to open the user profile. Clicking on a user name does not lead to any action. 

**Solution**
Same behavior as in regular channels.

**Comment by mrsimpson** [comment]
Fix provided. Still, in order to enable all users who are part of a request or expertise channel to add other users, a permission needs to be provided to the user role:
<img width="495" alt="permissions-add-user" src="https://user-images.githubusercontent.com/17176678/29836138-94ae31d0-8cf4-11e7-95b4-ab60cfd04c30.png">

This cannot be done via API. Created https://github.com/RocketChat/Rocket.Chat/issues/7961
